baseURL = "https://about.nakamasato.com/hugo-sample"
languageCode = "en-us"
title = "Hugo Sample"
themesDir = "themes"
theme = "hugo-whisper-theme"
# googleAnalytics = 'G-9NTB93RVPJ'
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

# Controls how many words are printed in the content summary on the docs homepage.
# See https://gohugo.io/content-management/summaries/
summaryLength = 30

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Docs"
    url = "/docs/"
    weight = 2

[params]
  google_analytics_id="G-9NTB93RVPJ"
  homepage_button_link = '/docs'
  homepage_button_text = 'Read The Docs'

  ## You can enable to add anchor links to header elements
  # enable_anchor_link = true

  [params.homepage_meta_tags]
    meta_description = "Hugo sample is built with whisper theme."
    meta_og_title = "Hugo sample"
    meta_og_type = "website"
    meta_og_url = "//nakamasato.github.io"
    meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-whisper-theme/master/images/tn.png"
    meta_og_description = "Hugo Whisper is a documentation theme built with Hugo."
    meta_twitter_card = "summary"
    meta_twitter_site = "@gymnstcs"
    meta_twitter_creator = "@gymnstcs"

  [params.logo]
      mobile = "/images/logo-mobile.svg"
      standard  = "/images/logo.svg"
